import { useState, type FormEvent } from 'react'
import { ArrowUpRight, Check, LoaderCircle } from 'lucide-react'
import { formEndpoint } from '../lib/config'
import { Reveal } from '../components/Reveal'
export default function Beta() {
 const [status, setStatus] = useState<'idle'|'sending'|'success'|'error'>('idle')
 const [message, setMessage] = useState('')
 async function submit(e: FormEvent<HTMLFormElement>) {
  e.preventDefault(); if (status === 'sending') return
  const form = e.currentTarget; const data = new FormData(form)
  if (!String(data.get('name')).trim() || !String(data.get('city')).trim()) { setStatus('error'); setMessage('Please enter your name and city.'); return }
  if (!/^https:\/\/formspree\.io\/f\/[a-zA-Z0-9]+$/.test(formEndpoint) || formEndpoint.includes('YOUR_FORM_ID')) { setStatus('error'); setMessage('Beta registration is being set up. Please check back soon. Your details have not been submitted.'); return }
  setStatus('sending'); setMessage('')
  try { const response = await fetch(formEndpoint, { method:'POST', body:data, headers:{Accept:'application/json'} }); if (!response.ok) throw new Error('Submission failed'); setStatus('success'); form.reset() } catch { setStatus('error'); setMessage('We couldn’t submit your signup. Please try again in a moment.') }
 }
 return <section id="beta" className="beta-section section"><div className="container beta-grid"><Reveal><p className="eyebrow"><span className="status-dot"/> EARLY INTEREST · OPEN</p><h2>Ride<br/>with us<span className="orange">.</span></h2><p className="section-copy">Help shape the future of wearable navigation for riders.</p><p className="beta-note">Join the list for development updates and opportunities to test a future prototype. No purchase. Just a shared direction.</p><div className="beta-signoff"><span className="small-arrow">↗</span><span>Better rides start<br/>with a new perspective.</span></div></Reveal><Reveal className="form-wrap">{status === 'success' ? <div className="success-panel" role="status"><Check size={36}/><h3>You’re on the list.</h3><p>Thanks for being part of Pivot’s next chapter. We’ll be in touch with development updates.</p><button className="text-link" onClick={() => setStatus('idle')}>Submit another signup <ArrowUpRight size={16}/></button></div> : <form onSubmit={submit}><div className="form-heading"><h3>Your next ride starts here.</h3><span>01 / EARLY ACCESS</span></div><div className="form-fields"><label>Name<input name="name" autoComplete="name" required maxLength={100} placeholder="Your name"/></label><label>Email<input name="email" type="email" autoComplete="email" required maxLength={254} placeholder="you@example.com"/></label><label>Rider type<select name="riderType" required defaultValue=""><option value="" disabled>Select your ride</option><option>Cyclist</option><option>E-scooter rider</option></select></label><label>City<input name="city" autoComplete="address-level2" required maxLength={100} placeholder="Where you ride"/></label></div><fieldset><legend>Would you test a future prototype?</legend><label className="radio-label"><input type="radio" name="prototypeTesting" value="Yes" required/> Yes, count me in</label><label className="radio-label"><input type="radio" name="prototypeTesting" value="No"/> Just here for updates</label></fieldset><input name="_gotcha" tabIndex={-1} autoComplete="off" className="honeypot" aria-hidden="true"/><button className="button button-primary form-submit" type="submit" disabled={status === 'sending'}>{status === 'sending' ? 'Submitting…' : 'Join the Beta'}{status === 'sending' ? <LoaderCircle size={18} className="spin"/> : <ArrowUpRight size={18}/>}</button><div role="status" aria-live="polite">{message && <p className="form-error">{message}</p>}</div><p className="form-privacy">By signing up, you agree to receive Pivot development and beta updates. Unsubscribe anytime. When enabled, signups are processed by Formspree. <a href="#privacy">Privacy details</a></p></form>}</Reveal></div></section>
}
