import { ArrowUpRight, ArrowRight, Navigation, MoveUpRight, Activity, Smartphone, Bluetooth, Vibrate, Bike, ChevronDown, Shield, Zap } from 'lucide-react'
import Navbar, { Logo } from './components/Navbar'
import { Reveal } from './components/Reveal'
import Beta from './sections/Beta'
import { assets } from './lib/config'
const faqs = [
 ['What is Pivot?', 'Pivot is a concept-stage arm-mounted wearable combining navigation guidance, visible turn signaling, and ride data for cyclists and e-scooter riders.'],
 ['Is Pivot available now?', 'Not yet. Pivot is in development. This is an early-interest list, not a preorder or a promise of a launch date.'],
 ['Who is it for?', 'Urban cyclists and e-scooter riders who want a more glanceable way to receive route guidance while riding.'],
 ['How does it work?', 'The planned design connects wirelessly to your phone. Your phone handles routing, while Pivot delivers navigation cues through lights, an interface, and haptics. Integration details are still being explored.'],
 ['What kind of information does it show?', 'The concept includes directional cues and useful ride information such as speed, distance, and trip duration. Final features will depend on design and prototype testing.'],
 ['How can I join the beta?', 'Fill out the form above to register early interest. We’ll share development updates and, when ready, future testing opportunities. Signing up does not guarantee a prototype or beta place.']
]
export default function App() {
 return <><a className="skip-link" href="#main">Skip to content</a><Navbar/><main id="main"><section className="hero"><img className="hero-image" src={assets.rider} alt="Pivot concept wearable with orange guidance lights, an elbow pad, and forearm section on a cyclist’s arm" width="1672" height="941" fetchPriority="high"/><div className="hero-shade"/><div className="container hero-content"><div className="hero-kicker"><span className="status-dot"/> A NEW DIRECTION FOR RIDERS</div><h1>Navigate<br/>without<br/>looking down<span className="orange">.</span></h1><p>Pivot is a wearable for cyclists and scooter riders that brings navigation, turn signaling, and ride data directly to your arm.</p><div className="hero-buttons"><a href="#beta" className="button button-primary">Join the Beta <ArrowUpRight size={18}/></a><a href="#how-it-works" className="button button-secondary">See How It Works <ArrowRight size={18}/></a></div></div><div className="hero-bottom container"><span><span className="status-dot"/> CONCEPT STAGE. FORWARD THINKING.</span><a href="#problem">SCROLL TO EXPLORE <span>↓</span></a></div><span className="image-caption">PRODUCT CONCEPT / VISUAL FOR ILLUSTRATION</span></section><div className="spec-strip"><div className="container"><span>LESS SCREEN. <span className="muted">MORE STREET.</span></span><span><Bike size={17}/> FOR CYCLISTS & E-SCOOTER RIDERS</span><span>DESIGNED TO KEEP YOU MOVING <ArrowUpRight size={17}/></span></div></div>
 <section id="problem" className="section problem-section"><Reveal className="container problem-grid"><p className="eyebrow">01 — A DIFFERENT PERSPECTIVE</p><div><h2>Phone navigation pulls<br/>your attention away<br/>from the <span className="muted">road.</span></h2><div className="problem-bottom"><div className="road-symbol" aria-hidden="true"><span/><span/><span/></div><p className="section-copy">The next turn. The traffic ahead. The phone in your pocket. Riding shouldn’t mean constantly switching focus.<br/><br/>Pivot is designed to move key information to your arm — making guidance more glanceable and your ride feel more connected.</p></div></div></Reveal></section>
 <section id="product" className="section features-section"><div className="container"><Reveal className="section-heading"><div><p className="eyebrow">02 — YOUR RIDE, IN FOCUS</p><h2>One wearable.<br/>A clearer direction.</h2></div><p className="section-copy">The essentials of your ride.<br/>Envisioned together, on your arm.</p></Reveal><div className="feature-grid">{[{Icon:Navigation,title:'Navigation',label:'KNOW YOUR NEXT MOVE',copy:'Turn-by-turn guidance designed to reduce the need to constantly check a phone.',visual:'↗'},{Icon:MoveUpRight,title:'Turn Signals',label:'MAKE YOUR INTENT VISIBLE',copy:'Visible directional indicators designed to help communicate where you’re headed.',visual:'‹ ‹ ‹'},{Icon:Activity,title:'Ride Data',label:'STAY IN THE LOOP',copy:'Useful ride information like speed, distance, and trip duration, in a glanceable format.',visual:'24.8'}].map(({Icon,title,label,copy,visual},i)=><Reveal key={title} className="feature"><div className={`feature-visual visual-${i}`} aria-hidden="true">{visual}{i===2 && <span>KM / H · CONCEPT DISPLAY</span>}</div><div className="feature-title"><Icon size={20}/><h3>{title}</h3><span>0{i+1}</span></div><p className="micro-label">{label}</p><p>{copy}</p></Reveal>)}</div><p className="concept-note">Planned features. Final functionality will evolve through development and testing.</p></div></section>
 <section id="how-it-works" className="section how-section"><div className="container"><Reveal className="section-heading"><div><p className="eyebrow">03 — A SIMPLE CONNECTION</p><h2>Your phone maps it.<br/><span className="muted">Pivot brings it closer.</span></h2></div><p className="section-copy">Your phone remains the source of route logic. Pivot is envisioned to translate that route into intuitive cues while you ride.</p></Reveal><Reveal className="flow">{[{Icon:Smartphone,title:'Set your route',copy:'Navigation starts on your phone.'},{Icon:Bluetooth,title:'Connect wirelessly',copy:'Your route connects to Pivot.'},{Icon:Zap,title:'Wear Pivot',copy:'Key information comes to your arm.'},{Icon:Vibrate,title:'Follow the cues',copy:'Lights, interface, and haptics guide you.'}].map(({Icon,title,copy},i)=><div className="flow-step" key={title}><div className="flow-icon"><Icon size={30} strokeWidth={1.3}/>{i<3&&<ArrowRight className="flow-arrow" size={20}/>}</div><span className="micro-label">0{i+1}</span><h3>{title}</h3><p>{copy}</p></div>)}</Reveal></div></section>
 <section className="section concept-section"><div className="container"><Reveal className="section-heading"><div><p className="eyebrow">04 — THE PRODUCT CONCEPT</p><h2>A wearable built<br/>for the road<span className="orange">.</span></h2></div><p className="section-copy">A connected form, from upper arm to forearm. Designed around wearability, visibility, and the way riders move.</p></Reveal><Reveal className="product-showcase"><img src={assets.product} alt="Studio concept views of Pivot, showing upper-arm directional lights, a contoured elbow pad, and a padded forearm module" width="1536" height="1024" loading="lazy"/><div className="product-image-label"><span className="status-dot"/> PIVOT / DESIGN STUDY 01 <span>CONCEPT RENDER</span></div></Reveal><div className="detail-grid">{[['01','Upper-arm guidance','Directional indicator lights designed to make rider intent visible.'],['02','Protective elbow design','A contoured elbow pad, with protection and freedom of movement as design priorities.'],['03','Forearm connection','Supportive padding paired with planned navigation and haptic functionality.']].map(([n,title,copy])=><Reveal className="product-detail" key={n}><span>{n}</span><div><h3>{title}</h3><p>{copy}</p></div></Reveal>)}</div><p className="concept-note"><Shield size={14}/> Protective performance has not been validated. Visuals illustrate the intended design.</p></div></section>
 <section className="section riders-section"><div className="container"><Reveal className="section-heading"><div><p className="eyebrow">05 — MADE FOR YOUR EVERYDAY</p><h2>Two wheels.<br/>Endless ways forward.</h2></div></Reveal><div className="rider-grid"><Reveal className="rider-card"><Bike size={45} strokeWidth={1}/><span className="micro-label">THE CITY IS YOUR ROUTE</span><h3>Cyclists</h3><p>From the morning commute to a new way home. Navigation cues and visible rider intent, designed for life on a bike.</p><span className="rider-card-bottom">PEDAL. CONNECT. EXPLORE. <ArrowUpRight size={22}/></span></Reveal><Reveal className="rider-card scooter-card"><svg width="48" height="45" viewBox="0 0 48 45" fill="none" stroke="currentColor" strokeWidth="1.3" aria-hidden="true"><circle cx="10" cy="35" r="6"/><circle cx="39" cy="35" r="6"/><path d="M10 35h23L27 9h-7M24 22L18 35M27 9h8"/></svg><span className="micro-label">MAKE EVERY BLOCK COUNT</span><h3>E-scooter riders</h3><p>Short trips. Busy streets. A wearable way to follow your route and communicate your next move across the city.</p><span className="rider-card-bottom">HOP ON. FIND YOUR WAY. <ArrowUpRight size={22}/></span></Reveal></div></div></section>
 <section id="vision" className="section vision-section"><div className="container"><Reveal className="vision-grid"><div><p className="eyebrow">06 — THE ROAD AHEAD</p><h2>From concept<br/>to the road.</h2></div><div><span className="development-badge"><span className="status-dot"/> CURRENTLY IN DEVELOPMENT</span><p className="section-copy">A clear vision. An evolving product.</p><p>We’re refining the Pivot concept and product direction, exploring how navigation, signaling, and protective design can work together in one wearable.</p><p>Early supporters will help inform what comes next. Join the list for future updates and prototype testing opportunities.</p></div></Reveal></div></section>
 <Beta/><section id="faq" className="section faq-section"><div className="container faq-grid"><Reveal><p className="eyebrow">07 — A FEW GOOD QUESTIONS</p><h2>Before your<br/>next turn.</h2><p className="section-copy">A little more about Pivot.</p></Reveal><div>{faqs.map(([q,a])=><details key={q} className="faq-item"><summary>{q}<ChevronDown size={19}/></summary><p>{a}</p></details>)}</div></div></section><section id="privacy" className="privacy-section container"><details><summary>Privacy & early-interest information</summary><p>Pivot requests your name, email, rider type, city, and prototype-testing preference to manage development updates and future research invitations. This form sends your information to Formspree for processing. We do not request payment information. You may unsubscribe from update emails or reply to them to request deletion. The signup is for early interest only and does not guarantee a beta place.</p></details></section></main><footer className="footer"><div className="container"><div className="footer-top"><div><a href="#" aria-label="Pivot home"><Logo/></a><p>Navigate without looking down.</p></div><div className="footer-links"><a href="#product">Product</a><a href="#how-it-works">How It Works</a><a href="#vision">Vision</a><a href="#beta">Join the Beta <ArrowUpRight size={14}/></a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Pivot</span><span>Concept-stage product. Visuals shown for illustration.</span><span>pivotride.work <span className="orange">↗</span></span></div></div></footer></>
}
